# https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions
name: Test action

on: [push]

jobs:
  test-file:
    name: Test action execution
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Create test file
        run: echo "foo" > release_file

      - name: Run current action
        uses: ./
        env:
          GITHUB_TOKEN: "TEST:TOKEN:HERE"
        with:
          file: './release_file'
          type: 'text/plain'
          dry: 'true'

      - name: Test dry run
        run: |
          cat ./upload_to_release_dry_run.debug
          DF="./upload_to_release_dry_run.debug"
          grep -Fxq "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${FILENAME}" "$DF"
          grep -Fxq "token TEST:TOKEN:HERE" "$DF"
          grep -Fxq "Content-Length: 4" "$DF"
          grep -Fxq "Content-Type: text/plain" "$DF"
          grep -Fxq "release_file" "$DF"
